# Generated by Django 3.1.4 on 2020-12-20 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('website', models.TextField()),
                ('company', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='blog.user')),
            ],
        ),
    ]
